apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260618-135143-uw780nx6x8pz-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260618-135143-uw780nx6x8pz.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260618-135143-uw780nx6x8pz-service
            port:
              number: 80
