apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260618-135143-uw780nx6x8pz-service
spec:
  selector:
    app: enterprise-system-20260618-135143-uw780nx6x8pz
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
